name: Go Live
on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  go_live:
    runs-on: ubuntu-latest
    name: Go Live
    steps:
      - uses: AlbertHernandez/go-live-action@v1.0.0
        with:
          required_labels: 'Merged in Beta;Tested in Beta'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}