name: Is Ready
on: [pull_request]
jobs:
  go_live:
    runs-on: ubuntu-latest
    name: Is Ready
    steps:
      - uses: AlbertHernandez/is-ready-action@v1.0.0
        with:
          required_labels: 'Merged in Beta;Tested in Beta'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
